# Generated by Django 5.2.8 on 2026-03-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_category_id_alter_division_id_alter_footer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='division',
        ),
        migrations.DeleteModel(
            name='footer',
        ),
    ]
