# Generated by Django 5.2.8 on 2026-03-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_delete_division_delete_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='car_body',
            field=models.CharField(max_length=255, verbose_name='кузов'),
        ),
        migrations.AlterField(
            model_name='products',
            name='drive',
            field=models.CharField(max_length=255, verbose_name='привод'),
        ),
        migrations.AlterField(
            model_name='products',
            name='fuel',
            field=models.CharField(max_length=255, verbose_name='топливо'),
        ),
        migrations.AlterField(
            model_name='products',
            name='gearbox',
            field=models.CharField(max_length=255, verbose_name='коробка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='model',
            field=models.CharField(max_length=255, verbose_name='модель'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='volume',
            field=models.CharField(max_length=255, verbose_name='объем'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='fuel_info',
            field=models.CharField(max_length=255, verbose_name='информация о топливе'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='info',
            field=models.CharField(max_length=1000, verbose_name='информация'),
        ),
    ]
