# Generated by Django 5.2.8 on 2026-03-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_year', models.IntegerField(verbose_name='Год рождения')),
                ('has_driver_license', models.BooleanField(verbose_name='Есть водительские права')),
            ],
        ),
    ]
