# Generated by Django 5.2.8 on 2026-03-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='birth_year',
            field=models.DateTimeField(verbose_name='год рождение'),
        ),
    ]
