# Generated by Django 5.2.8 on 2026-03-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_alter_dealer_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='has_driver_license',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='dealer',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес дилера'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта дилера'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название дилера'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон дилера'),
        ),
    ]
