# Generated by Django 5.2.8 on 2026-03-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_drive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdrive',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
    ]
