# Generated by Django 5.2.8 on 2026-03-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_drive', '0002_testdrive_email_alter_testdrive_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
