# Generated by Django 5.2.8 on 2026-03-13 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_products_car_body_alter_products_drive_and_more'),
        ('test_drive', '0003_alter_testdrive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TestDrive', to='api.products'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='date',
            field=models.DateTimeField(verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='name',
            field=models.CharField(max_length=100, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='номер телефона'),
        ),
    ]
