# Generated by Django 5.2.8 on 2026-03-13 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_products_car_body_alter_products_drive_and_more'),
        ('test_drive', '0005_alter_testdrive_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='api.products'),
        ),
    ]
