# Generated by Django 5.2.8 on 2026-03-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_drive', '0006_alter_testdrive_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='phone',
            field=models.CharField(max_length=9, verbose_name='номер телефона'),
        ),
    ]
