# Generated by Django 5.2.8 on 2026-03-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_products_car_body_alter_products_drive_and_more'),
        ('dealer', '0002_alter_dealer_birth_year'),
        ('test_drive', '0007_alter_testdrive_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdrive',
            name='car',
        ),
        migrations.AddField(
            model_name='testdrive',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='dealer.dealer', verbose_name='Дилер (ID)'),
        ),
        migrations.AddField(
            model_name='testdrive',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_drives', to='api.products', verbose_name='Продукт (ID)'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='date',
            field=models.DateTimeField(verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='phone',
            field=models.CharField(help_text='Номер должен начинаться с +996', max_length=13, verbose_name='Номер телефона'),
        ),
    ]
